/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHistory: typeof import('./components/shared/ChatHistory.vue')['default']
    ChatInput: typeof import('./components/shared/ChatInput.vue')['default']
    DocChatPanel: typeof import('./components/document_workspace/DocChatPanel.vue')['default']
    DocumentModule: typeof import('./components/document_workspace/DocumentModule.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    KnowledgeTree: typeof import('./components/shared/KnowledgeTree.vue')['default']
    LeftPanel: typeof import('./components/shared/LeftPanel.vue')['default']
    LoadingScreen: typeof import('./components/common/LoadingScreen.vue')['default']
    MessageBubble: typeof import('./components/shared/MessageBubble.vue')['default']
    MessageInput: typeof import('./components/shared/MessageInput.vue')['default']
    MeteorShower: typeof import('./components/common/MeteorShower.vue')['default']
    RightPanelContent: typeof import('./components/shared/RightPanelContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadModal: typeof import('./components/common/UploadModal.vue')['default']
    VideoCentrePanel: typeof import('./components/video_workspace/VideoCentrePanel.vue')['default']
  }
}
